/* DON'T MAKE ANY CHARACTERISTICS(MACROSES) MORE. YOU SHOULD USE ONLY THIS CHARACTERISTICS */

#define TASKSLEN 100        /* MAX TASKS LENGTH IN TASK LIST */
#define TASKLEN  100        /* MAX LENGTH OF TASK(<= 1024 or it can't works fine) */
#define NAMELEN  100        /* MAX LENGTH OF NAME YOUR USABLE TASK LIST */
#define NOTASKS	 "No tasks" /* NO TASKS TEXT RESULT */
#define EDITOR   "nano"     /* EDITOR FOR -E */
